# Generated by Django 3.1.7 on 2022-06-05 17:58

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210515_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension], verbose_name='Изображение')),
                ('favorite_is', models.BooleanField(default=False)),
            ],
        ),
    ]
