# Generated by Django 3.1.7 on 2022-06-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220606_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_is',
        ),
    ]
